version: '2'
services:
  web:
    build: .
    command: /opt/bin/multistreamer -l /usr/bin/lua -e development run
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  redis:
    image: redis
    hostname: redis
    expose:
      - "6379"

  db:
    image: postgres
    hostname: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=multistreamer
      - POSTGRES_PASSWORD=multistreamer
      - POSTGRES_DB=multistreamer


